server:
    port: 9595

spring:
    profiles: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: Awards


    mail:
        baseUrl: http://localhost:9595
        host: smtp.gmail.com
        port: 587
        user: chile-payroll-process@nisum.com
        password: Pc@1230#
        protocol: smtp
        tls: true
        auth: true
        from: awards.notification.center@nisum.com

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: Awards


