server:
    port: 8080

spring:
    profiles: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: Awards


    mail:
        baseUrl: http://localhost:8080
        host: smtp.gmail.com
        port: 587
        user: xxx@gmail.com
        password:
        protocol: smtp
        tls: true
        auth: true
        from: xx@gmail.com

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: Awards


