server:
    port: 8080

spring:
    profiles: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: Awards


    mail:
        baseUrl: http://localhost:8080
        host: smtp.gmail.com
        port: 587
        user: awards.notification.center@gmail.com
        password: demo12345
        protocol: smtp
        tls: true
        auth: true
        from: awards.notification.center@gmail.com

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: Awards


